syntax = "proto3";

package gopass;

option csharp_namespace = "Gopass";
option go_package = "../proto";

// The GoPassService defines the service methods.
service GopassService {

    // List returns a list of all secrets.
    rpc ListSecrets (ListRequest) returns (ListResponse);
    
    // Get returns a single, encrypted secret.
    rpc GetSecret (GetRequest) returns (GetResponse);
    
    // Set adds a new revision to an existing secret or creates a new one.
    rpc SetSecret (SetRequest) returns (SetResponse);
    
    // Remove removes a single secret.
    rpc RemoveSecret (RemoveRequest) returns (RemoveResponse);
    
    // RemoveAll removes all secrets with a given prefix.
    rpc RemoveAllSecretsWithPrefix (RemoveAllRequest) returns (RemoveAllResponse);
    
    // Rename moves a prefix to another.
    rpc RenameSecret (RenameRequest) returns (RenameResponse);

    // Authenticates the user with the given credentials.
    rpc Authenticate (AuthRequest) returns (AuthResponse);
}

// Request and response types

message ListRequest {}

message ListResponse {
    repeated string secrets = 1;
}

message GetRequest {
    string name = 1;
    string revision = 2;
}

message GetResponse {
    string secret = 1; // The encrypted secret
}

message SetRequest {
    string name = 1;
    string secret = 2; // The encrypted secret
}

message SetResponse {}

message RemoveRequest {
    string name = 1;
}

message RemoveResponse {}

message RemoveAllRequest {
    string prefix = 1;
}

message RemoveAllResponse {}

message RenameRequest {
    string src = 1;
    string dest = 2;
}

message RenameResponse {}

message AuthRequest {
    string passphrase = 1;
}

message AuthResponse {
    string status = 1;
}
