// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: gopass.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command arguments (first element is the gopass subcommand)
	Args []string `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	// Working directory for the command
	WorkingDir string `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	// Environment variables
	EnvVars map[string]string `protobuf:"bytes,3,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Timeout in seconds (0 means no timeout)
	TimeoutSeconds int32 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_gopass_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopass_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_gopass_proto_rawDescGZIP(), []int{0}
}

func (x *CommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CommandRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *CommandRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *CommandRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type CommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Standard output
	Stdout string `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Standard error
	Stderr string `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// Exit code (0 means success)
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Success flag
	Success bool `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if command couldn't be executed
	ErrorMessage string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Execution time in milliseconds
	ExecutionTimeMs int64 `protobuf:"varint,6,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_gopass_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopass_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_gopass_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CommandResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

type CommandOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output data (stdout or stderr)
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Whether this is from stderr
	IsStderr bool `protobuf:"varint,2,opt,name=is_stderr,json=isStderr,proto3" json:"is_stderr,omitempty"`
	// Whether this is the final message
	IsFinal bool `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// Exit code (only set in final message)
	ExitCode int32 `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Error message (only set in final message)
	ErrorMessage  string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOutput) Reset() {
	*x = CommandOutput{}
	mi := &file_gopass_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutput) ProtoMessage() {}

func (x *CommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_gopass_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutput.ProtoReflect.Descriptor instead.
func (*CommandOutput) Descriptor() ([]byte, []int) {
	return file_gopass_proto_rawDescGZIP(), []int{2}
}

func (x *CommandOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommandOutput) GetIsStderr() bool {
	if x != nil {
		return x.IsStderr
	}
	return false
}

func (x *CommandOutput) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *CommandOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandOutput) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CommandInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command arguments (only in first message)
	Args []string `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	// Input data to send to process
	Input []byte `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	// Whether to close stdin after this message
	CloseStdin bool `protobuf:"varint,3,opt,name=close_stdin,json=closeStdin,proto3" json:"close_stdin,omitempty"`
	// Working directory (only in first message)
	WorkingDir string `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	// Environment variables (only in first message)
	EnvVars map[string]string `protobuf:"bytes,5,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Whether to cancel the command
	Cancel        bool `protobuf:"varint,6,opt,name=cancel,proto3" json:"cancel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandInput) Reset() {
	*x = CommandInput{}
	mi := &file_gopass_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandInput) ProtoMessage() {}

func (x *CommandInput) ProtoReflect() protoreflect.Message {
	mi := &file_gopass_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandInput.ProtoReflect.Descriptor instead.
func (*CommandInput) Descriptor() ([]byte, []int) {
	return file_gopass_proto_rawDescGZIP(), []int{3}
}

func (x *CommandInput) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CommandInput) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *CommandInput) GetCloseStdin() bool {
	if x != nil {
		return x.CloseStdin
	}
	return false
}

func (x *CommandInput) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *CommandInput) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *CommandInput) GetCancel() bool {
	if x != nil {
		return x.Cancel
	}
	return false
}

var File_gopass_proto protoreflect.FileDescriptor

const file_gopass_proto_rawDesc = "" +
	"\n" +
	"\fgopass.proto\x12\x06gopass\"\xea\x01\n" +
	"\x0eCommandRequest\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\x12>\n" +
	"\benv_vars\x18\x03 \x03(\v2#.gopass.CommandRequest.EnvVarsEntryR\aenvVars\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x01\n" +
	"\x0fCommandResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12*\n" +
	"\x11execution_time_ms\x18\x06 \x01(\x03R\x0fexecutionTimeMs\"\x9d\x01\n" +
	"\rCommandOutput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tis_stderr\x18\x02 \x01(\bR\bisStderr\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\x8c\x02\n" +
	"\fCommandInput\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\x12\x1f\n" +
	"\vclose_stdin\x18\x03 \x01(\bR\n" +
	"closeStdin\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12<\n" +
	"\benv_vars\x18\x05 \x03(\v2!.gopass.CommandInput.EnvVarsEntryR\aenvVars\x12\x16\n" +
	"\x06cancel\x18\x06 \x01(\bR\x06cancel\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xef\x01\n" +
	"\rGopassService\x12C\n" +
	"\x0eExecuteCommand\x12\x16.gopass.CommandRequest\x1a\x17.gopass.CommandResponse\"\x00\x12I\n" +
	"\x14ExecuteCommandStream\x12\x16.gopass.CommandRequest\x1a\x15.gopass.CommandOutput\"\x000\x01\x12N\n" +
	"\x19ExecuteInteractiveCommand\x12\x14.gopass.CommandInput\x1a\x15.gopass.CommandOutput\"\x00(\x010\x01B\x13Z\b../proto\xaa\x02\x06Gopassb\x06proto3"

var (
	file_gopass_proto_rawDescOnce sync.Once
	file_gopass_proto_rawDescData []byte
)

func file_gopass_proto_rawDescGZIP() []byte {
	file_gopass_proto_rawDescOnce.Do(func() {
		file_gopass_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gopass_proto_rawDesc), len(file_gopass_proto_rawDesc)))
	})
	return file_gopass_proto_rawDescData
}

var file_gopass_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gopass_proto_goTypes = []any{
	(*CommandRequest)(nil),  // 0: gopass.CommandRequest
	(*CommandResponse)(nil), // 1: gopass.CommandResponse
	(*CommandOutput)(nil),   // 2: gopass.CommandOutput
	(*CommandInput)(nil),    // 3: gopass.CommandInput
	nil,                     // 4: gopass.CommandRequest.EnvVarsEntry
	nil,                     // 5: gopass.CommandInput.EnvVarsEntry
}
var file_gopass_proto_depIdxs = []int32{
	4, // 0: gopass.CommandRequest.env_vars:type_name -> gopass.CommandRequest.EnvVarsEntry
	5, // 1: gopass.CommandInput.env_vars:type_name -> gopass.CommandInput.EnvVarsEntry
	0, // 2: gopass.GopassService.ExecuteCommand:input_type -> gopass.CommandRequest
	0, // 3: gopass.GopassService.ExecuteCommandStream:input_type -> gopass.CommandRequest
	3, // 4: gopass.GopassService.ExecuteInteractiveCommand:input_type -> gopass.CommandInput
	1, // 5: gopass.GopassService.ExecuteCommand:output_type -> gopass.CommandResponse
	2, // 6: gopass.GopassService.ExecuteCommandStream:output_type -> gopass.CommandOutput
	2, // 7: gopass.GopassService.ExecuteInteractiveCommand:output_type -> gopass.CommandOutput
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gopass_proto_init() }
func file_gopass_proto_init() {
	if File_gopass_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gopass_proto_rawDesc), len(file_gopass_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gopass_proto_goTypes,
		DependencyIndexes: file_gopass_proto_depIdxs,
		MessageInfos:      file_gopass_proto_msgTypes,
	}.Build()
	File_gopass_proto = out.File
	file_gopass_proto_goTypes = nil
	file_gopass_proto_depIdxs = nil
}
