// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: gopass.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GopassService_ExecuteCommand_FullMethodName            = "/gopass.GopassService/ExecuteCommand"
	GopassService_ExecuteCommandStream_FullMethodName      = "/gopass.GopassService/ExecuteCommandStream"
	GopassService_ExecuteInteractiveCommand_FullMethodName = "/gopass.GopassService/ExecuteInteractiveCommand"
)

// GopassServiceClient is the client API for GopassService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GopassServiceClient interface {
	// Run a gopass command and get the result
	ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	// Run a command and stream the output
	ExecuteCommandStream(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommandOutput], error)
	// Interactive command with input and output streams
	ExecuteInteractiveCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandInput, CommandOutput], error)
}

type gopassServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGopassServiceClient(cc grpc.ClientConnInterface) GopassServiceClient {
	return &gopassServiceClient{cc}
}

func (c *gopassServiceClient) ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, GopassService_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopassServiceClient) ExecuteCommandStream(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommandOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GopassService_ServiceDesc.Streams[0], GopassService_ExecuteCommandStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommandRequest, CommandOutput]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GopassService_ExecuteCommandStreamClient = grpc.ServerStreamingClient[CommandOutput]

func (c *gopassServiceClient) ExecuteInteractiveCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandInput, CommandOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GopassService_ServiceDesc.Streams[1], GopassService_ExecuteInteractiveCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommandInput, CommandOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GopassService_ExecuteInteractiveCommandClient = grpc.BidiStreamingClient[CommandInput, CommandOutput]

// GopassServiceServer is the server API for GopassService service.
// All implementations must embed UnimplementedGopassServiceServer
// for forward compatibility.
type GopassServiceServer interface {
	// Run a gopass command and get the result
	ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error)
	// Run a command and stream the output
	ExecuteCommandStream(*CommandRequest, grpc.ServerStreamingServer[CommandOutput]) error
	// Interactive command with input and output streams
	ExecuteInteractiveCommand(grpc.BidiStreamingServer[CommandInput, CommandOutput]) error
	mustEmbedUnimplementedGopassServiceServer()
}

// UnimplementedGopassServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGopassServiceServer struct{}

func (UnimplementedGopassServiceServer) ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedGopassServiceServer) ExecuteCommandStream(*CommandRequest, grpc.ServerStreamingServer[CommandOutput]) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteCommandStream not implemented")
}
func (UnimplementedGopassServiceServer) ExecuteInteractiveCommand(grpc.BidiStreamingServer[CommandInput, CommandOutput]) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteInteractiveCommand not implemented")
}
func (UnimplementedGopassServiceServer) mustEmbedUnimplementedGopassServiceServer() {}
func (UnimplementedGopassServiceServer) testEmbeddedByValue()                       {}

// UnsafeGopassServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GopassServiceServer will
// result in compilation errors.
type UnsafeGopassServiceServer interface {
	mustEmbedUnimplementedGopassServiceServer()
}

func RegisterGopassServiceServer(s grpc.ServiceRegistrar, srv GopassServiceServer) {
	// If the following call pancis, it indicates UnimplementedGopassServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GopassService_ServiceDesc, srv)
}

func _GopassService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopassServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopassService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopassServiceServer).ExecuteCommand(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopassService_ExecuteCommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GopassServiceServer).ExecuteCommandStream(m, &grpc.GenericServerStream[CommandRequest, CommandOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GopassService_ExecuteCommandStreamServer = grpc.ServerStreamingServer[CommandOutput]

func _GopassService_ExecuteInteractiveCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GopassServiceServer).ExecuteInteractiveCommand(&grpc.GenericServerStream[CommandInput, CommandOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GopassService_ExecuteInteractiveCommandServer = grpc.BidiStreamingServer[CommandInput, CommandOutput]

// GopassService_ServiceDesc is the grpc.ServiceDesc for GopassService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GopassService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gopass.GopassService",
	HandlerType: (*GopassServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler:    _GopassService_ExecuteCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteCommandStream",
			Handler:       _GopassService_ExecuteCommandStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecuteInteractiveCommand",
			Handler:       _GopassService_ExecuteInteractiveCommand_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gopass.proto",
}
